name: newman using trello

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Create Reports Directory
        run: mkdir -p newman

      - name: Run Newman Collection
        run: |
          newman run TRELLO.postman_collection.json \
            -r cli,json,junit,htmlextra \
            --reporter-json-export newman/report.json \
            --reporter-junit-export newman/report.xml \
            --reporter-htmlextra-export newman/report.html \
            --global-var "TRELLO_API_KEY=${{ secrets.TRELLO_API_KEY }}" \
            --global-var "TRELLO_API_TOKEN=${{ secrets.TRELLO_API_TOKEN }}"

      - name: Upload Newman Reports
        uses: actions/upload-artifact@v4
        with:
          name: newman-reports
          path: newman/
