name: newman using trello

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Newman
        run: npm install -g newman

      - name: Install htmlextra
        run: npm install -g newman-reporter-htmlextra

      - name: Run Newman Collection
        run: |
          newman run TRELLO.postman_collection.json -r "cli,json,junit,htmlextra" \
          --global-var "TRELLO_API_KEY=${{ secrets.TRELLO_API_KEY }}" \
          --global-var "TRELLO_API_TOKEN=${{ secrets.TRELLO_API_TOKEN }}"

      - uses:  actions/upload-artifact@v2
        with: 
              name: newman-reports
              path: ./newman
